
services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETPLATFORM=linux/amd64
    # platform: linux/amd64
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"  # Spark Master Web UI
      - "7077:7077"  # Spark Master port
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_LOG_DIR=/tmp
    entrypoint: ["/bin/sh", "-c", "/usr/local/spark/sbin/start-master.sh --ip 0.0.0.0 && tail -f /dev/null"]
    networks:
      - spark-network

  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - TARGETPLATFORM=linux/amd64
    # platform: linux/amd64
    container_name: spark-worker-1
    hostname: spark-worker-1
    user: "root:root"
    depends_on:
      - spark-master
    ports:
      - "8081:8081"  # Worker 1 Web UI
    volumes:
      - ./data:/home/jovyan/data
      - ./results:/home/jovyan/results
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_LOG_DIR=/tmp/spark-logs1
      - SPARK_WORKER_DIR=/tmp/spark-work1
    entrypoint: ["/bin/sh", "-c", "mkdir -p /tmp/spark-work && chmod 777 /tmp/spark-work && /usr/local/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"]
    networks:
      - spark-network

  spark-worker-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETPLATFORM=linux/amd64
    # platform: linux/amd64
    container_name: spark-worker-2
    hostname: spark-worker-2
    user: "root:root"
    depends_on:
      - spark-master
    ports:
      - "8082:8081"  # Worker 2 Web UI
    volumes:
      - ./data:/home/jovyan/data
      - ./results:/home/jovyan/results
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_LOG_DIR=/tmp/spark-logs2
      - SPARK_WORKER_DIR=/tmp/spark-work2
    entrypoint: ["/bin/sh", "-c", "/usr/local/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"]
    networks:
      - spark-network

  spark-worker-3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETPLATFORM=linux/amd64
    # platform: linux/amd64
    container_name: spark-worker-3
    hostname: spark-worker-3
    user: "root:root"
    depends_on:
      - spark-master
    ports:
      - "8083:8081"  
    volumes:
      - ./data:/home/jovyan/data
      - ./results:/home/jovyan/results
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_LOG_DIR=/tmp/spark-logs3
      - SPARK_WORKER_DIR=/tmp/spark-work3
    entrypoint: ["/bin/sh", "-c", "/usr/local/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"]
    networks:
      - spark-network

  spark-worker-4:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETPLATFORM=linux/amd64
    # platform: linux/amd64
    container_name: spark-worker-4
    hostname: spark-worker-4
    user: "root:root"
    depends_on:
      - spark-master
    ports:
      - "8084:8081" 
    volumes:
      - ./data:/home/jovyan/data
      - ./results:/home/jovyan/results
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_LOG_DIR=/tmp/spark-logs4
      - SPARK_WORKER_DIR=/tmp/spark-work4
    entrypoint: ["/bin/sh", "-c", "/usr/local/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"]
    networks:
      - spark-network

  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGETPLATFORM=linux/amd64
    # platform: linux/amd64
    container_name: jupyterlab
    ports:
      - "8888:8888"  # JupyterLab interface
      - "4040:4040"  # Spark Application UI

    volumes:
      - .:/home/jovyan
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_IP=0.0.0.0
      - JUPYTER_PORT=8888
      - JUPYTER_TOKEN=""  # Set to empty string for no token
      - JUPYTER_PASSWORD=""  # Set to empty string for no password
      - JUPYTER_DISABLE_AUTH=true # Disable authentication
    networks:
      - spark-network
    depends_on:
      - spark-master

networks:
  spark-network:
    driver: bridge