version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: ubuntu_dev
    volumes:
      - ./:/app
    ports:
      # Add ports as needed for your applications
      - "8080:8080"
      - "3000:3000"
      - "8888:8888"  # JupyterLab port
    environment:
      - TZ=UTC
    # Keep the container running
    tty: true
    stdin_open: true
    # Restart policy
    restart: unless-stopped